sonar.projectKey=v-s-v-i-s-h-w-a-s_task-manager-api
sonar.organization=v-s-v-i-s-h-w-a-s

# sonar-project.properties
sonar.projectName=task-manager-api
sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=task-manager-api
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
