sonar.projectKey=v-s-v-i-s-h-w-a-s_task-manager-api
sonar.organization=v-s-v-i-s-h-w-a-s

# sonar-project.properties
sonar.projectName=Task Manager API
sonar.language=py

# Optional but recommended:
sonar.sources=.
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/migrations/**
sonar.test.inclusions=tests/**/*.py

# Ensure proper branch recognition
sonar.branch.name=${GITHUB_REF_NAME}

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=task-manager-api
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
